[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
eggsistential = "2cATotAz8hga1PfPHXpAeapd1WFMMnB9AgY4DNWjX62k"

[programs.localnet]
eggsistential = "8cfSNA3TQjzWazzU9D7UEMSs8NeT27D35fkxPmonMyzd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/eggsistential/Cargo.toml"
